### PR TITLE
ssh-keys: update to set of people actively working on the infra-core

### PR DESCRIPTION
**Pull request by RaitoBezarius**
In a context where we are reminded of how critical is it to apply the least privilege, it's always good to maintain our most critical infrastructures.

I tried to reach out to @grahamc and @AmineChikhaoui to no avail.
We discussed this with @edolstra during last infrastructure meeting, and they consented to the effects of this PR.

PTAL @zimbatm @mweinelt.

### CODE REVIEW

**Review by mweinelt — APPROVED** [review]

**Review by JulienMalka — APPROVED** [review]

**Comment by AmineChikhaoui** [comment]
Hey @RaitoBezarius , sorry didn't notice where you pinged me. But feel free to remove my ssh key. Happy to help when needed but I haven't really used it for a while.

**Comment by vcunat** [comment]
IIRC at the end of the meeting Eelco said he'd need to think about it, and I see no issue with keeping him in there.

**Comment by vcunat** [comment]
It would be nice to get @delroth back, but obviously only if he'll want to.

**Comment by delroth** [comment]
> It would be nice to get @delroth back, but obviously only if he'll want to.

The foundation board isn't in a hurry, so I'm not in a hurry either.

**Comment by RaitoBezarius** [comment]
> IIRC at the end of the meeting Eelco said he'd need to think about it, and I see no issue with keeping him in there.

I don't think Eelco is contributing nowadays to the infrastructure and as I said, I think it makes sense to apply the principle of the least privilege here. So I'm inclined to maintain the same contents for now, except if there's a good reason not to?

**Pull request merged**
